### ISSUE TITLE
add support in the code completion menu

### ISSUE THREAD

**Issue by AngryCarrot789** [chylex/IntelliJ-Forge-Mapping-Hints#1]
this plugin is amazing... but if it had support to show the mapped name (e.g markTileEntityChunkModified) in the code completion menu, that would make it so much better

**Comment by chylex** [comment]
This plugin is obsolete. The most that'll happen with it is that it will be partly repurposed as a [Parchment](https://github.com/ParchmentMC) parameter/javadoc mapping tool, since we've moved over to official mojang mappings and don't do fields/methods anymore.

**Comment by AngryCarrot789** [comment]
oh well. but still, great plugin. very useful, especially when using mods in plugins because having to work on searge mappings and search them up in the mappings file was a bit of a faf
